name    'jbregman-summon'
version '0.1.0'
source 'UNKNOWN'
author 'jbregman'
license 'Apache License, Version 2.0'
summary 'UNKNOWN'
description 'UNKNOWN'
project_page 'UNKNOWN'

## Add dependencies, if any:
dependency 'stankevich/python', '>= 1.11.0'
dependency 'puppetlabs/git', '>= 0.4.0'
